### ISSUE TITLE
Poetry is somehow thinking there is a version of this library called 2fa-0.3.0

### ISSUE THREAD

**Issue by djackson-exo-inc** [suutari/drf-jwt-2fa#11]
And this is causing install issues on GitHub Actions since it does not actually exist. Can you please advise?

**Comment by djackson-exo-inc** [comment]
ERROR: Could not find a version that satisfies the requirement drf-jwt-2fa==2fa-0.3.0 (from versions: 0.1.0, 0.2.0, 0.3.0)
ERROR: No matching distribution found for drf-jwt-2fa==2fa-0.3.0

**Comment by suutari** [comment]
I'm pretty sure that this issue is in your pyproject.toml, Poetry lock file or in Poetry itself. Can't find anything to fix here. Please reopen, if you find that there's something in drf-jwt-2fa packages that can be fixed regarding this.
